language: java

branches:
  only:
    - master

script:
  "mvn clean package"

install:
  ""

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)